dist: xenial
sudo: required

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
virtualenv:
  system_site_packages: false

cache: pip

env:
    - FLAKE8=false

jobs:
  include:
  - python: 3.5
    env: FLAKE8=true

install:
    # Dependencies
    - sudo apt-get -qq update
    - pip install --upgrade -qq pip
    - sudo apt-get -qq install cdparanoia cdrdao flac gir1.2-glib-2.0 libcdio-dev libgirepository1.0-dev libiso9660-dev libsndfile1-dev sox swig libcdio-utils libdiscid0 python3-pil
    # newer version of pydcio requires newer version of libcdio than travis has
    - pip install pycdio==0.21
    # install rest of dependencies
    - pip install -r requirements.txt

    # Testing dependencies
    - pip install twisted flake8

    # Installing
    - python setup.py install

script:
    - if [ ! "$FLAKE8" = true ]; then python -m unittest discover; fi
    - if [ "$FLAKE8" = true ]; then flake8 --benchmark --statistics; fi
